"use client";

import { useEffect, useState } from "react";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { fetchApi } from "@/lib/api";
import { Download, FileText } from "lucide-react";

export default function ReportsPage() {
  const [reports, setReports] = useState<any[]>([]);

  useEffect(() => {
    fetchApi<any[]>("/reports")
      .then((data) => setReports(data || []))
      .catch(() => setReports([]));
  }, []);

  return (
    <div className="min-h-screen bg-background flex text-on-surface">
      <Sidebar />
      <div className="pl-64 flex flex-col min-h-screen w-full">
        <Header />

        <main className="relative pt-14 flex-1 w-full bg-surface px-space-xl py-space-lg space-y-space-lg">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pt-4">
            <div>
              <h1 className="font-headline-lg text-2xl font-bold text-on-surface">Compliance Reports & Dossier Exporter</h1>
              <p className="text-xs text-secondary">Generated PDF compliance dossiers and CSV risk summaries</p>
            </div>
          </div>

          <div className="bg-surface-container-lowest rounded-xl p-space-lg border border-outline-variant/30 space-y-4">
            {reports.length === 0 ? (
              <div className="p-12 text-center space-y-3 bg-surface rounded-xl border border-outline-variant/30">
                <FileText className="w-8 h-8 text-secondary mx-auto" />
                <h3 className="font-bold text-sm text-on-surface">No Exported Dossiers Yet</h3>
                <p className="text-xs text-secondary max-w-sm mx-auto">
                  Dossier reports generated after statutory officer decisions will appear here for download.
                </p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs text-on-surface">
                  <thead className="bg-surface border-b border-outline-variant/40 font-bold uppercase text-secondary">
                    <tr>
                      <th className="py-3 px-4">Report Name</th>
                      <th className="py-3 px-4">Type</th>
                      <th className="py-3 px-4">Generated By</th>
                      <th className="py-3 px-4">Date</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-outline-variant/30">
                    {reports.map((r, idx) => (
                      <tr key={idx} className="hover:bg-surface-container-low transition-colors">
                        <td className="py-3.5 px-4 font-mono font-medium flex items-center gap-2">
                          <FileText className="w-4 h-4 text-primary" />
                          <span>{r.report_name}</span>
                        </td>
                        <td className="py-3.5 px-4 font-semibold text-secondary">{r.report_type}</td>
                        <td className="py-3.5 px-4 text-secondary">{r.generated_by || "System"}</td>
                        <td className="py-3.5 px-4 text-secondary">{r.generated_at}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </main>
      </div>
    </div>
  );
}
